### ISSUE TITLE
Starting masternode with UI or usual cli commands doesn't work

### ISSUE THREAD

**Issue by ksamuel** [digiwage/digiwage#1]
If we use the QT-wallet to start-alias a masternode, we get an error stating the IP is invalid.

If we use the debug console with the usual "masternode start-alias 'name'", it will print an error with a help message.

Reading the help message I tried several combinations until I found that "startmasternode alias lockwallet 'name'" would work.

Kevin, from Tetricoins

**Comment by digiwage** [comment]
you should use this command to start a MN
startmasternode alias false <Name of your MN>
