### ISSUE TITLE
Daemon shutdown without any error message

### ISSUE THREAD

**Issue by Alex-1357** [digiwage/digiwage#7]
my customer ask me to start Digiwage daemon with his mastrnodekey
unfortunately your daemon shutdown after 1-2 second without any error or warning to console
config look as correct

![Docker_01222022_220101-1](https://user-images.githubusercontent.com/86534217/150654014-cf9a640d-4a62-4d19-b993-42bf9f53108b.png)

Is there verbose parameters to understand reason of shutdown your daemon?

**Comment by gdiscord** [comment]
This is was because you are running the wallet in docker in daemon mode. 
To resolve ensure you add daemon=0 in your digiwage.conf file.
